import = [ "~/.config/alacritty/themes/themes/catppuccin_mocha.toml" ]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.5
padding = { x = 18, y = 16 }
dynamic_padding = false
decorations = "buttonless"
blur = true
option_as_alt = "Both"

[font]
normal = { family = "ShureTechMono Nerd Font", style = "Regular" }
#normal = { family = "Hack Nerd Font", style = "Regular" }
size = 15.0

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_timeout = 0
unfocused_hollow = false
blink_interval = 300

[keyboard]
bindings = [{ key = "Right", mods = "Alt", chars = "\u001BF"},
		{ key = "Left", mods = "Alt", chars = "\u001BB"},
		{key = "End",mods = "Shift",action = "ScrollToBottom"},
		{key = "Home", mods ="Shift", action = "ScrollToTop"}]
#{ key = "Left", mods = "Alt", action = "WordLeft"}]
#	{ key = "Left", mods = "Alt", chars = "\u001BB"}]
#	    { key = "Right", mods = "Alt", chars = "\u004BF"}]
#not working for word right \u001BF
#  - {key: Right, mods: Alt, chars: "\ef"}
#  - {key: Left, mods: Control, chars: "\eb"}
#  - {key: Right, mods: Control, chars: "\ef"}
